language: cpp

sudo: false

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.5

env:
  global:
   - MAPNIK_GIT: v3.0.0-rc1-693-g01a9b4c

before_install:
 - export CXX="clang++-3.5"
 - export CC="clang-3.5"
 - python --version

install:
 - time python setup.py build

before_script:
 - true

script:
 - true
