language: cpp

git:
  submodules: true
  depth: 10

sudo: false

cache:
  directories:
  - mason_packages
  - $HOME/.ccache

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.5

before_install:
 - export MASON_BUILD=true
 - if [[ $(uname -s) == 'Linux' ]]; then
     export CXX="ccache clang++-3.5 -Qunused-arguments";
     export CC="ccache clang++-3.5 -Qunused-arguments";
     export PYTHONPATH=$(pwd)/mason_packages/.link/lib/python2.7/site-packages;
   else
     export PYTHONPATH=$(pwd)/mason_packages/.link/lib/python/site-packages;
   fi;
 - PYTHONUSERBASE=$(pwd)/mason_packages/.link pip install --user nose
 - python --version

install:
 - time python setup.py build

before_script:
 - python test/run_tests.py -q

script:
 - python test/visual.py -q
