language: cpp

git:
  submodules: true
  depth: 10

matrix:
  include:
     - os: linux
       compiler: clang
     - os: osx
       compiler: clang

env:
  global:
    - secure: "CqhZDPctJcpXGPpmIPK5usD/O+2HYawW3434oDufVS9uG/+C7aHzKzi8cuZ7n/REHqJMzy7gJfp6DiyF2QowpnN1L2W0FSJ9VOgj4JQF2Wsupo6gJkq6/CW2Fa35PhQHsv29bfyqtIq+R5SBVAieBe/Lh2P144RwRliGRopGQ68="
    - secure: "idk4fdU49i546Zs6Fxha14H05eRJ1G/D6NPRaie8M8o+xySnEqf+TyA9/HU8QH7cFvroSLuHJ1U7TmwnR+sXy4XBlIfHLi4u2MN+l/q014GG7T2E2xYcTauqjB4ldToRsDQwe5Dq0gZCMsHLPspWPjL9twfp+Ds7qgcFhTsct0s="

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.5

before_install:
 - pip install twine
 - export COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
 - export MASON_BUILD=true
 - if [[ $(uname -s) == 'Linux' ]]; then
     export CXX="clang++-3.5";
     export CC="clang++-3.5";
     export PYTHONPATH=$(pwd)/mason_packages/.link/lib/python2.7/site-packages;
   else
     export PYTHONPATH=$(pwd)/mason_packages/.link/lib/python/site-packages;
   fi;
 - PYTHONUSERBASE=$(pwd)/mason_packages/.link pip install --user nose
 - python --version

install:
 - time python setup.py build

before_script:
 - python test/run_tests.py -q

script:
 - python test/visual.py -q
 - if [[ ${COMMIT_MESSAGE} =~ "[publish]" ]]; then
    python setup.py bdist_wheel;
    export DISTS='dist/*';
    twine -u $PYPI_USER -p $PYPI_PASSWORD $DISTS ;
   fi;
